---
- name: kernel - add backports repo
  apt_repository: repo='deb http://ftp.debian.org/debian/ wheezy-backports main non-free contrib' update_cache=yes state=present
  sudo: yes

- name: kernel - install backported kernel
  apt: pkg="linux-image-{{ docker_debian_kernel_arch }}" default_release='wheezy-backports' state=latest
  sudo: yes

- name: kernel - add cgroup options to kernel boot arguments
  lineinfile: dest=/etc/default/grub line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"' state=present
  register: grub
  sudo: yes

- name: kernel - update grub and reboot
  shell: shutdown -r now
  when: grub|changed
  register: reboot
  sudo: yes

- name: kernel - wait for reboot
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host }}"
    port: "{{ ansible_ssh_port | default(22) }}"
    delay: 30
    timeout: 600
    state: started
